name: 💡 General Feature Request
description: Have a new idea/feature for the website? Please suggest!
title: '[FEATURE] <description>'
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose, also include what you tried and what worked.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Screenshots if applicable
    validations:
      required: false
